services:
  sfu:
    build: ./sfu
    restart: unless-stopped
    env_file: ./sfu/.env
    ports:
      - "3000:3000"
      - "10000-10100:10000-10100/udp"
    networks:
      - voice-with-me-network
      - nginx-proxy

  turn:
    build: ./turn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - turn-logs:/var/log/turnserver
    command: -c /etc/coturn/turnserver.conf

volumes:
  turn-logs:

networks:
  voice-with-me-network:
    driver: bridge
  nginx-proxy:
    external: true
